name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14.17.6'

    - name: Install packages
      id: install-packages
      run: npm install

    - name: Flow check
      id: flow-check
      run: npm run flow

    - name: Linting
      id: linting
      run: npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: linting
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14.17.6'

    - name: Install packages
      id: install-packages
      run: npm install
    
    - name: Deploy react app to github pages
      id: deploy-react-app
      env:
        email: ${{ secrets.GH_EMAIL }}
        name: ${{ secrets.GH_NAME }}
      run: |
        git config --global user.email $email
        git config --global user.name $name
        git remote set-url origin https://github.com/thesct22/thesct22.github.io.git
        npm run deploy